language: r
r: bioc-devel
cache:
  packages: true
  directories:
    - ~/.AnnotationHub
sudo: required
warnings_are_errors: true
dist: trusty

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 [xerus] it is part of libnetcdf-dev)
      - libhdf5-dev
      - libgit2-dev # git2r
        

